// GENERATED by backend/legal/build.ts from store/privacy/*.md. Do not edit by hand.
import type { LegalContent } from "./handler.ts";

export const LEGAL: LegalContent = {
  "privacy": {},
  "terms": {},
  "support": {}
};
