"""growth_* — viral TikTok/Reels slideshow generator (SlideSmith pattern, NO Postbridge).

The step AFTER the app is submitted (post-launch growth). Logic:
  1. Viral hook + slide texts → generated by CLAUDE (in the pipeline, no extra LLM/cost).
  2. Slide images → generated by the app's OWN AI (fal: nano-banana before/after + flux background)
     (NO Pinterest scraping; on-brand, copyright-free).
  3. Slides are rendered (sharp): 1080x1920 vertical, hook text overlay → marketing/growth/<set>/NN.png.
  4. NO scheduling (Postbridge is paid) — the user shares the output manually/for free.

Usage: Claude prepares the slideshows list → growth_build_slideshows renders it.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

import httpx

from . import config as cfg
from .proc import run


def _gen_image(prompt: str, ref_data_uri: str | None, out: Path) -> bool:
    """Generate a slide image with fal. If ref_data_uri is given, face-preserving (nano-banana edit)."""
    fal = cfg.load_config().get("fal_key")
    if not fal:
        return False
    try:
        if ref_data_uri:
            r = httpx.post("https://fal.run/fal-ai/nano-banana/edit",
                           headers={"Authorization": f"Key {fal}", "Content-Type": "application/json"},
                           json={"prompt": prompt, "image_urls": [ref_data_uri]}, timeout=180)
        else:
            r = httpx.post("https://fal.run/fal-ai/flux/schnell",
                           headers={"Authorization": f"Key {fal}", "Content-Type": "application/json"},
                           json={"prompt": prompt, "image_size": "portrait_16_9"}, timeout=120)
        url = (r.json().get("images") or [{}])[0].get("url")
        if not url:
            return False
        out.write_bytes(httpx.get(url, timeout=120).content)
        return True
    except Exception:  # noqa: BLE001
        return False


_RENDER_JS = r"""
import sharp from "sharp";
import fs from "node:fs/promises";
const [,, specPath] = process.argv;
const spec = JSON.parse(await fs.readFile(specPath, "utf-8"));
const W = 1080, H = 1920;
function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");}
function wrap(t, n){const w=t.split(" ");let l=[],c="";for(const x of w){if((c+" "+x).trim().length>n){l.push(c.trim());c=x;}else c+=" "+x;}if(c.trim())l.push(c.trim());return l;}
for (const slide of spec.slides) {
  const lines = wrap(slide.text||"", 22);
  const fs0 = lines.length>3?70:88;
  const tspans = lines.map((ln,i)=>`<tspan x="${W/2}" dy="${i===0?0:fs0*1.18}">${esc(ln)}</tspan>`).join("");
  const overlay = Buffer.from(`<svg width="${W}" height="${H}">
    <defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="rgba(0,0,0,0.55)"/><stop offset="40%" stop-color="rgba(0,0,0,0.0)"/>
      <stop offset="70%" stop-color="rgba(0,0,0,0.0)"/><stop offset="100%" stop-color="rgba(0,0,0,0.6)"/></linearGradient></defs>
    <rect width="${W}" height="${H}" fill="url(#g)"/>
    <text x="${W/2}" y="220" text-anchor="middle" font-family="-apple-system,Helvetica,Arial,sans-serif"
      font-size="${fs0}" font-weight="800" fill="#ffffff" stroke="rgba(0,0,0,0.35)" stroke-width="2">${tspans}</text>
    ${slide.cta?`<text x="${W/2}" y="${H-120}" text-anchor="middle" font-family="-apple-system,Helvetica,Arial,sans-serif" font-size="44" font-weight="600" fill="#ffffff">${esc(slide.cta)}</text>`:""}
  </svg>`);
  let base = sharp(slide.image).resize(W, H, { fit: "cover" });
  const buf = await base.png().toBuffer();
  await sharp(buf).composite([{ input: overlay, top: 0, left: 0 }]).png().toFile(slide.out);
}
console.log("rendered " + spec.slides.length);
"""


def build_slideshows(app_dir: str | Path, slideshows: list[dict]) -> dict[str, Any]:
    """Render slideshow sets. slideshows = [{name, slides:[{text, image_prompt?, image?, cta?}]}].
    If image_prompt is given, generated with fal; if image is given (e.g. a sample in Resources), that is used.
    Output: <app_dir>/marketing/growth/<name>/NN.png (1080x1920, ready to share)."""
    app = Path(app_dir).expanduser()
    gdir = app / "marketing" / "growth"
    sshots = app / "marketing" / "screenshots"  # sharp node_modules live here
    tmp = gdir / "_tmp"
    tmp.mkdir(parents=True, exist_ok=True)
    results = []
    for sset in slideshows:
        name = sset["name"]
        out = gdir / name
        shutil.rmtree(out, ignore_errors=True)
        out.mkdir(parents=True, exist_ok=True)
        spec_slides = []
        for i, sl in enumerate(sset.get("slides", [])):
            img = sl.get("image")
            if not img and sl.get("image_prompt"):
                p = tmp / f"{name}_{i}.png"
                if _gen_image(sl["image_prompt"], sl.get("ref_data_uri"), p):
                    img = str(p)
            if not img:
                continue
            spec_slides.append({"image": img, "text": sl.get("text", ""),
                                "cta": sl.get("cta"), "out": str(out / f"{i + 1:02d}.png")})
        spec = tmp / f"{name}_spec.json"
        spec.write_text(json.dumps({"slides": spec_slides}), encoding="utf-8")
        # write render.mjs into the screenshots dir + run it from there (so sharp node_modules resolve)
        js = sshots / "_growth_render.mjs"
        js.write_text(_RENDER_JS, encoding="utf-8")
        r = run(["node", str(js), str(spec)], timeout=300, cwd=str(sshots))
        js.unlink(missing_ok=True)
        results.append({"name": name, "slides": len(spec_slides), "ok": r.get("ok"), "dir": str(out)})
    shutil.rmtree(tmp, ignore_errors=True)
    return {"ok": all(x["ok"] for x in results) if results else False, "sets": results}
