import SwiftUI
import UIKit

/// What the mascot is doing. Raw values == `app.spec.json` design.mascot.states and the asset names
/// the factory imports (`mascot_assets` → Resources/Assets.xcassets/Mascot/<state>{,-blink}.imageset).
enum MascotState: String, CaseIterable {
    case idle, wave, cheer, think, love, snap, trophy, sleep

    /// The approved pose art this state animates (namespaced asset folder `Mascot`).
    var poseAsset: String { "Mascot/\(rawValue)" }

    /// The pixel-aligned closed-eye copy of the pose (made by `mascot_blink`), if it exists.
    var blinkAsset: String? {
        let name = "Mascot/\(rawValue)-blink"
        return UIImage(named: name) != nil ? name : nil
    }

    /// True once the approved poses are imported; before that the view shows a placeholder symbol.
    var hasArt: Bool { UIImage(named: poseAsset) != nil }

    fileprivate var motion: MascotMotion {
        switch self {
        case .idle: return .idle
        case .wave: return .wave
        case .cheer: return .cheer
        case .think: return .think
        case .love: return .love
        case .snap: return .snap
        case .trophy: return .trophy
        case .sleep: return .sleep
        }
    }
}

/// The app mascot, animated natively from the motion boards (design/project/M01…M08, generated by
/// `design_generate`): whole-pose transforms around the feet (50 % / 96 %), a blink by swapping in the
/// closed-eye copy at ~90–93 % of the loop (double blink for idle), and per-state overlays.
/// LESSON: animate the APPROVED pose PNGs — never rig from a separately generated parts sheet (it
/// drifts off-model). Reduce Motion and UI tests show the still pose; below 60 pt only breathing and
/// blinking run. Missing assets render a placeholder symbol so the template always builds.
struct MascotView: View {
    let state: MascotState
    var size: CGFloat = 120

    @Environment(\.motionReduced) private var reducedFlag
    @Environment(\.accessibilityReduceMotion) private var systemReduced
    @State private var start = Date()

    private var reduced: Bool { reducedFlag || systemReduced }

    var body: some View {
        Group {
            if !state.hasArt {
                placeholder
            } else if reduced {
                frame(MascotPoseFrame.still(state.motion))
            } else {
                TimelineView(.animation) { context in
                    frame(MascotPoseFrame(state.motion, t: context.date.timeIntervalSince(start), effects: size >= 60))
                }
            }
        }
        .frame(width: size, height: size)
        .accessibilityHidden(true)
    }

    private var placeholder: some View {
        Image(systemName: state == .sleep ? "moon.zzz.fill" : "face.smiling.inverse")
            .resizable()
            .scaledToFit()
            .padding(size * 0.18)
            .foregroundStyle(DS.Palette.primary)
            .bob(duration: 2.6, amplitude: size * 0.04)
    }

    private func frame(_ f: MascotPoseFrame) -> some View {
        let k = size / 290   // the spec is drawn on a 290 pt stage
        return ZStack {
            ZStack {
                image(state.poseAsset)
                if let blink = state.blinkAsset {
                    image(blink).opacity(f.blink)
                }
                if f.gleam != nil {
                    TrophyGleam(progress: f.gleam ?? 0, scale: k)
                        .mask(image(state.poseAsset))
                }
            }
            .rotationEffect(.degrees(f.rotation), anchor: UnitPoint(x: 0.5, y: 0.96))
            .scaleEffect(x: f.scaleX, y: f.scaleY, anchor: UnitPoint(x: 0.5, y: 0.96))
            .offset(y: f.translateY * k)
            ForEach(Array(f.overlays.enumerated()), id: \.offset) { _, o in
                overlay(o, k: k)
            }
        }
        .frame(width: size, height: size)
    }

    private func image(_ name: String) -> some View {
        Image(name).resizable().scaledToFit().frame(width: size, height: size)
    }

    @ViewBuilder
    private func overlay(_ o: MascotOverlay, k: CGFloat) -> some View {
        switch o.kind {
        case .confetti(let color):
            RoundedRectangle(cornerRadius: 3 * k).fill(color)
                .frame(width: 9 * k, height: 14 * k)
                .rotationEffect(.degrees(o.rotation))
                .position(x: o.x * k, y: o.y * k)
        case .sparkle(let pt):
            Text(verbatim: "✦").font(.system(size: pt * k, weight: .heavy)).foregroundStyle(Color(0xFFC53D))
                .scaleEffect(o.scale).rotationEffect(.degrees(o.rotation)).opacity(o.opacity)
                .position(x: o.x * k, y: o.y * k)
        case .heart(let pt):
            Image(systemName: "heart.fill").resizable().foregroundStyle(Color(0xFF6B8B)).frame(width: pt * k, height: pt * k * 22 / 24)
                .scaleEffect(o.scale).opacity(o.opacity)
                .position(x: o.x * k, y: o.y * k)
        case .zee(let pt):
            Text(verbatim: "z").font(.system(size: pt * k, weight: .heavy, design: .rounded)).foregroundStyle(Color(0x8B7CF6))
                .scaleEffect(o.scale).opacity(o.opacity)
                .position(x: o.x * k, y: o.y * k)
        case .flash:
            Circle()
                .fill(RadialGradient(stops: [.init(color: .white, location: 0), .init(color: .white.opacity(0.85), location: 0.3),
                                             .init(color: .white.opacity(0), location: 0.7)], center: .center, startRadius: 0, endRadius: 65 * k))
                .frame(width: 130 * k, height: 130 * k)
                .scaleEffect(o.scale).opacity(o.opacity)
                .position(x: o.x * k, y: o.y * k)
        case .bubble(let dots):
            ThoughtBubble(dots: dots, k: k).scaleEffect(o.scale, anchor: UnitPoint(x: 0.1, y: 1))
                .position(x: o.x * k, y: o.y * k)
        case .bubbleDot(let d):
            Circle().fill(.white).overlay(Circle().stroke(DS.Palette.foreground, lineWidth: 2.5 * k))
                .frame(width: d * k, height: d * k)
                .position(x: o.x * k, y: o.y * k)
        }
    }
}

// MARK: - Motion model

fileprivate enum MascotMotion { case idle, wave, cheer, think, love, snap, trophy, sleep }

fileprivate struct MascotOverlay {
    enum Kind {
        case confetti(Color), sparkle(CGFloat), heart(CGFloat), zee(CGFloat), flash
        case bubble([CGFloat]), bubbleDot(CGFloat)
    }
    var kind: Kind
    /// Center, in the 290 pt stage.
    var x: CGFloat
    var y: CGFloat
    var scale: CGFloat = 1
    var opacity: Double = 1
    var rotation: Double = 0
}

/// One frame of a state at time `t` (seconds), straight from the CSS keyframes.
fileprivate struct MascotPoseFrame {
    var scaleX: CGFloat = 1
    var scaleY: CGFloat = 1
    var translateY: CGFloat = 0
    var rotation: Double = 0
    var blink: Double = 0
    var gleam: Double?
    var overlays: [MascotOverlay] = []

    static func still(_ m: MascotMotion) -> MascotPoseFrame {
        var f = MascotPoseFrame()
        if m == .sleep {
            f.blink = 1
            f.rotation = -3
        }
        return f
    }

    init() {}

    init(_ m: MascotMotion, t: Double, effects: Bool) {
        switch m {
        case .idle:
            let b = K.at(t, 3.2, [(0, 0), (0.5, 1), (1, 0)])
            scaleX = 1 + 0.012 * b; scaleY = 1 + 0.028 * b
            rotation = K.at(t, 6.4, [(0, -1.4), (0.5, 1.4), (1, -1.4)])
            blink = K.doubleBlink(t, 6.4)
        case .wave:
            rotation = K.at(t, 1.1, [(0, -3.5), (0.5, 3.5), (1, -3.5)])
            translateY = K.at(t, 1.1, [(0, 0), (0.2, -8), (0.4, 0), (1, 0)])
            blink = K.blink(t, 4.4)
        case .cheer:
            translateY = K.at(t, 0.9, [(0, 0), (0.14, 0), (0.5, -46), (0.86, 0), (1, 0)])
            scaleX = K.at(t, 0.9, [(0, 1.07), (0.14, 0.97), (0.5, 1), (0.86, 1), (1, 1.07)])
            scaleY = K.at(t, 0.9, [(0, 0.93), (0.14, 1.04), (0.5, 1), (0.86, 1), (1, 0.93)])
            rotation = K.at(t, 0.9, [(0, -2.5), (0.5, 2.5), (1, -2.5)])
            blink = K.blink(t, 3.6)
            if effects {
                let colors: [UInt] = [0xF0612B, 0xFFC53D, 0x8B7CF6, 0x35C07A, 0xFF7EB6]
                for i in 0..<12 {
                    let duration = 1.6 + Double(i % 4) * 0.25
                    let p = K.phase(t + (Double(i) * 0.37).truncatingRemainder(dividingBy: 1.8), duration)
                    overlays.append(MascotOverlay(kind: .confetti(Color(colors[i % 5])), x: CGFloat(14 + i * 28 - 35) + 4.5,
                                                  y: -78 + 7 + 500 * p, rotation: 560 * p))
                }
            }
        case .think:
            rotation = K.at(t, 4, [(0, -2), (0.5, 2.5), (1, -2)])
            let b = K.at(t, 4, [(0, 0), (0.5, 1), (1, 0)])
            scaleX = 1 + 0.01 * b; scaleY = 1 + 0.02 * b
            blink = K.blink(t, 4)
            if effects {
                let dots = (0..<3).map { i in CGFloat(K.at(t - Double(i) * 0.15, 1.2, [(0, 0), (0.4, 1), (1, 0)])) }
                overlays.append(MascotOverlay(kind: .bubbleDot(9), x: 212 + 4.5, y: 60 + 4.5))
                overlays.append(MascotOverlay(kind: .bubbleDot(14), x: 219 + 7, y: 42 + 7))
                overlays.append(MascotOverlay(kind: .bubble(dots), x: 237 + 31, y: -14 + 24,
                                              scale: 1 + 0.05 * K.at(t, 4, [(0, 0), (0.5, 1), (1, 0)])))
            }
        case .love:
            let s = K.at(t, 1.4, [(0, 1), (0.12, 1.045), (0.24, 0.99), (0.32, 1.03), (0.4, 1), (1, 1)])
            let sy = K.at(t, 1.4, [(0, 1), (0.12, 1.035), (0.24, 0.99), (0.32, 1.03), (0.4, 1), (1, 1)])
            scaleX = s; scaleY = sy
            rotation = K.at(t, 2.8, [(0, -1.6), (0.5, 1.6), (1, -1.6)])
            blink = K.blink(t, 4.2)
            if effects {
                for (x, y, d, pt) in [(25.0, 92.0, 0.0, 22.0), (247, 72, 0.9, 18), (215, 142, 1.8, 26), (5, 172, 2.3, 16)] {
                    let p = K.phase(t - d, 2.8)
                    let rise = K.easeOut(p)
                    overlays.append(MascotOverlay(kind: .heart(pt), x: x + pt / 2, y: y + pt / 2 + 30 - 120 * rise,
                                                  scale: 0.4 + 0.7 * rise, opacity: p < 0.2 ? p / 0.2 : 1 - (p - 0.2) / 0.8))
                }
            }
        case .snap:
            let keys: [(Double, Double)] = [(0, 0), (0.3, 0), (0.38, 1), (0.46, 2), (0.56, 3), (1, 3)]
            let seg = K.at(t, 2.4, keys, eased: false)
            let sx: [Double] = [1, 0.97, 1.03, 1], sy: [Double] = [1, 1.03, 0.97, 1], r: [Double] = [0, -1.5, 1, 0]
            scaleX = K.lerpSegments(seg, sx); scaleY = K.lerpSegments(seg, sy); rotation = K.lerpSegments(seg, r)
            if effects {
                let p = K.phase(t, 2.4)
                let flash: (Double, Double) = p < 0.4 ? (0, 0.4) : p < 0.44 ? ((p - 0.4) / 0.04, 0.4 + 0.6 * (p - 0.4) / 0.04)
                    : p < 0.7 ? (1 - (p - 0.44) / 0.26, 1 + 0.5 * (p - 0.44) / 0.26) : (0, 1.5)
                overlays.append(MascotOverlay(kind: .flash, x: 81, y: 112, scale: flash.1, opacity: flash.0))
                for (x, y, d) in [(235.0, 192.0, 0.0), (265, 158, 0.12), (197, 232, 0.22)] {
                    let q = K.phase(t - d, 2.4)
                    let (o, s, rot) = K.twinkleSnap(q)
                    overlays.append(MascotOverlay(kind: .sparkle(20), x: x + 8, y: y + 10, scale: s, opacity: o, rotation: rot))
                }
            }
        case .trophy:
            translateY = K.at(t, 1.6, [(0, 0), (0.1, 0), (0.3, -22), (0.5, 0), (0.55, 0), (1, 0)])
            scaleX = K.at(t, 1.6, [(0, 1), (0.1, 1.05), (0.3, 0.98), (0.5, 1.02), (0.55, 1), (1, 1)])
            scaleY = K.at(t, 1.6, [(0, 1), (0.1, 0.95), (0.3, 1.02), (0.5, 0.98), (0.55, 1), (1, 1)])
            rotation = K.at(t, 3.2, [(0, -1.5), (0.5, 1.5), (1, -1.5)])
            if effects {
                let p = K.phase(t, 1.6)
                gleam = p < 0.4 ? 0 : p < 0.8 ? K.smooth((p - 0.4) / 0.4) : 1
                for (x, y, d) in [(265.0, 2.0, 0.0), (215, -14, 0.5), (283, 70, 1.0)] {
                    let q = K.at(t - d, 1.6, [(0, 0), (0.5, 1), (1, 0)])
                    overlays.append(MascotOverlay(kind: .sparkle(18), x: x + 7, y: y + 9, scale: 0.6 + 0.55 * q,
                                                  opacity: 0.2 + 0.8 * q, rotation: 20 * q))
                }
            }
        case .sleep:
            rotation = -3
            blink = 1
            let b = K.at(t, 4.4, [(0, 0), (0.45, 1), (1, 0)])
            scaleX = 1 + 0.02 * b; scaleY = 1 + 0.04 * b; translateY = -2 * b
            if effects {
                for (d, pt) in [(0.0, 18.0), (1.47, 24), (2.93, 30)] {
                    let p = K.phase(t - d, 4.4)
                    let e = K.easeOut(p)
                    overlays.append(MascotOverlay(kind: .zee(pt), x: 201 + 34 * e + pt / 3, y: 38 + 20 - 90 * e + pt / 2,
                                                  scale: 0.5 + 0.65 * e, opacity: p < 0.2 ? p / 0.2 : 1 - (p - 0.2) / 0.8))
                }
            }
        }
    }
}

/// Keyframe math for the CSS animations.
fileprivate enum K {
    /// 0…1 position in a cycle of `period` seconds.
    static func phase(_ t: Double, _ period: Double) -> Double {
        let p = (t / period).truncatingRemainder(dividingBy: 1)
        return p < 0 ? p + 1 : p
    }

    static func smooth(_ x: Double) -> Double { x * x * (3 - 2 * x) }
    static func easeOut(_ x: Double) -> Double { 1 - (1 - x) * (1 - x) }

    /// Value at time `t` of keyframes (fraction, value), ease-in-out between stops.
    static func at(_ t: Double, _ period: Double, _ stops: [(Double, Double)], eased: Bool = true) -> Double {
        let p = phase(t, period)
        for i in 1..<stops.count where p <= stops[i].0 {
            let (a, va) = stops[i - 1], (b, vb) = stops[i]
            let x = b > a ? (p - a) / (b - a) : 1
            return va + (vb - va) * (eased ? smooth(x) : x)
        }
        return stops.last?.1 ?? 0
    }

    /// Interpolates a fractional segment index across values.
    static func lerpSegments(_ s: Double, _ values: [Double]) -> Double {
        let i = min(values.count - 2, max(0, Int(s)))
        let x = smooth(min(1, max(0, s - Double(i))))
        return values[i] + (values[i + 1] - values[i]) * x
    }

    /// `blink`: closed between 91 % and 92.5 % of the cycle.
    static func blink(_ t: Double, _ period: Double) -> Double {
        let p = phase(t, period)
        return (p >= 0.9 && p <= 0.935) ? (p < 0.91 ? (p - 0.9) / 0.01 : p > 0.925 ? (0.935 - p) / 0.01 : 1) : 0
    }

    /// `dblink`: two quick blinks at 85 % and 90 %.
    static func doubleBlink(_ t: Double, _ period: Double) -> Double {
        let p = phase(t, period)
        func pulse(_ c: Double) -> Double {
            let d = abs(p - c)
            return d <= 0.004 ? 1 : d <= 0.01 ? (0.01 - d) / 0.006 : 0
        }
        return max(pulse(0.85), pulse(0.9))
    }

    /// `tw` of the snap board: hidden until 50 %, pops at 62 %, gone by 90 %.
    static func twinkleSnap(_ p: Double) -> (Double, CGFloat, Double) {
        if p < 0.5 { return (0, 0.3, 0) }
        if p < 0.62 { let x = (p - 0.5) / 0.12; return (x, 0.3 + 0.8 * x, 30 * x) }
        if p < 0.9 { let x = (p - 0.62) / 0.28; return (1 - x, 1.1 - 0.5 * x, 30 + 30 * x) }
        return (0, 0.6, 60)
    }
}

/// The thinking bubble with three bouncing dots (62 × 48 on the stage).
private struct ThoughtBubble: View {
    let dots: [CGFloat]
    let k: CGFloat

    var body: some View {
        HStack(spacing: 5 * k) {
            ForEach(dots.indices, id: \.self) { i in
                Circle().fill(DS.Palette.foreground).frame(width: 8 * k, height: 8 * k)
                    .offset(y: -4 * k * dots[i])
                    .opacity(0.35 + 0.65 * Double(dots[i]))
            }
        }
        .frame(width: 62 * k, height: 48 * k)
        .background(Capsule().fill(.white))
        .overlay(Capsule().stroke(DS.Palette.foreground, lineWidth: 2.5 * k))
    }
}

/// The white sweep over the trophy (stage rect 186, 38, 70 × 88), masked by the pose art.
private struct TrophyGleam: View {
    let progress: Double
    let scale: CGFloat

    var body: some View {
        GeometryReader { geo in
            let k = geo.size.width / 290
            let x = 186 * k + (-0.6 + 1.9 * progress) * 70 * k
            LinearGradient(colors: [.white.opacity(0), .white.opacity(0.9), .white.opacity(0)], startPoint: .leading, endPoint: .trailing)
                .frame(width: 28 * k, height: 124 * k)
                .rotationEffect(.degrees(20))
                .position(x: x + 14 * k, y: (38 + 44) * k)
                .mask(RoundedRectangle(cornerRadius: 18 * k).frame(width: 70 * k, height: 88 * k).position(x: (186 + 35) * k, y: (38 + 44) * k))
        }
        .allowsHitTesting(false)
    }
}

#if DEBUG
/// `-uiMascotGallery`: every state side by side, for the #15 UI test and visual review.
struct MascotGallery: View {
    var body: some View {
        ScrollView {
            LazyVGrid(columns: [GridItem(.adaptive(minimum: 110), spacing: 8)], spacing: 16) {
                ForEach(MascotState.allCases, id: \.self) { state in
                    VStack(spacing: 4) {
                        MascotView(state: state, size: 110)
                        Text(verbatim: state.rawValue).font(.caption.bold())
                    }
                    .accessibilityElement(children: .ignore)
                    .accessibilityLabel(Text(verbatim: state.rawValue))
                    .accessibilityIdentifier("mascot_\(state.rawValue)")
                }
            }
            .padding(.top, 70)
            .padding(.horizontal, 12)
        }
        .background(DS.Palette.background.ignoresSafeArea())
    }
}
#endif
