"""Regenerate docs/TOOLS.md from src/appfactory/server.py (tool names, first docstring paragraph, service gating).

    python docs/gen_tools.py
"""
import ast
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
tree = ast.parse((ROOT / "src/appfactory/server.py").read_text(encoding="utf-8"))

services: dict[str, tuple[str, ...]] = {}
for node in tree.body:
    if isinstance(node, ast.AnnAssign) and getattr(node.target, "id", "") == "TOOL_SERVICES":
        # evaluate with the module-level `_APPLE` alias and dict/set unpacking resolved
        services = eval(compile(ast.Expression(node.value), "TOOL_SERVICES", "eval"), {"_APPLE": ("apple",)})

groups: dict[str, list[tuple[str, str]]] = defaultdict(list)
for node in tree.body:
    if isinstance(node, ast.FunctionDef) and any(getattr(d, "id", "") == "tool" for d in node.decorator_list):
        para = (ast.get_docstring(node) or "").strip().split("\n\n")[0]
        summary = " ".join(para.split()).rstrip(".")
        if len(summary) > 180:
            summary = summary[:177].rsplit(" ", 1)[0] + "..."
        need = ", ".join(services.get(node.name, ())) or "none"
        groups[node.name.split("_")[0]].append((node.name, f"{summary} | {need}"))

out = ["# Tool reference", "",
       "Generated by `python docs/gen_tools.py` from `src/appfactory/server.py`; do not edit by hand.",
       "Tools whose service is disabled return `service_disabled` and do nothing (see the README).", ""]
for prefix in sorted(groups):
    out += [f"## {prefix}", "", "| Tool | What it does | Needs service |", "|---|---|---|"]
    for name, rest in groups[prefix]:
        summary, need = rest.rsplit(" | ", 1)
        out.append(f"| `{name}` | {summary.replace('|', '/')} | {need} |")
    out.append("")
(ROOT / "docs/TOOLS.md").write_text("\n".join(out), encoding="utf-8")
print(f"{sum(map(len, groups.values()))} tools -> docs/TOOLS.md")
